config/routes.rb
Rails.application.routes.draw do
  resources :categories, except: :show
  resources :products, path: "/"
  # patch '/products/:id', to: 'products#update'
  # delete '/products/:id', to: 'products#destroy'
  # post '/products', to: 'products#create'
  # get '/products', to: 'products#index'
  # get 'products/new', to: 'products#new', as: 'new_product'
  # get 'products/:id', to: 'products#show', as: 'product'
  # get 'products/:id/edit', to: 'products#edit', as: 'edit_product'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :restrict_with_exception
end

app/models/product.rb
class Product < ApplicationRecord
    has_one_attached :photo
    
    validates :title, presence: true
    validates :description, presence: true
    validates :price, presence: true

    belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #Todo esto lo añadimos para obtener el lenguaje configura del navegador del usuario.
  around_action :switch_locale

  def switch_locale(&action)
    I18n.with_locale(locale_from_header, &action)
  end

  private

  def locale_from_header
    request.env["HTTP_ACCEPT_LANGUAGE"]&.scan(/^[a-z]{2}/)&.first
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all.order(name: :asc)
  end

  def new
    @category = Category.new
  end

  def edit
    category
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path, notice: t(".created")
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if category.update(category_params)
      redirect_to categories_path, notice: t(".updated")
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    category.destroy
    redirect_to categories_path, notice: t(".destroyed"), status: :see_other #para evitar un 302 automatico y que falle turbo le pasamos un 303.
  end

  private

  def category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all.with_attached_photo.order(created_at: :desc)
  end

  def show
    product
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path, notice: t(".created")
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    product
  end

  def update
    if product.update(product_params)
      redirect_to products_path, notice: t(".updated")
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    product.destroy
    redirect_to products_path, notice: t(".destroyed"), status: :see_other #para evitar un 302 automatico y que falle turbo le pasamos un 303.
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :price, :photo, :category_id)
  end

  def product
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <%= category.name %>
  <%= link_to t(".edit"), edit_category_path(category) %>
  <%= link_to t(".delete"), category_path(category), data: {
                                                       turbo_method: :delete,
                                                       turbo_confirm: t("common.confirm"),
                                                     } %>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% @category.errors.full_messages.each do |error| %>
    <p><%= error %></p>
  <% end %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1><%= t(".title") %>:</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to t("common.back"), categories_path %>
</div>

app/views/categories/index.html.erb
<h1><%= t(".title") %>:</h1>

<%= render partial: "category", collection: @categories %>

<%= link_to t(".new"), new_category_path %>

app/views/categories/new.html.erb
<h1><%= t(".title") %>:</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to t("common.back"), categories_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vendelo - CRUD de prueba con Rails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render "shared/header" %>
    <%= render "shared/flash" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with model: @product do |form| %>
  <% @product.errors.full_messages.each do |error| %>
    <p><%= error %></p>
  <% end %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
  <div>
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>
  <div>
    <%= form.label :category_id %>
    <%= form.collection_select :category_id, Category.all.order(name: :asc), :id, :name %>
  </div>
  <div>
    <%= form.label :photo %>
    <%= form.file_field :photo %>
  </div>
    <%= form.submit %>
<% end %>

app/views/products/_product.html.erb
<div class="product">
    <h3><%= link_to product.title, product_path(product.id) %></h3>
    <%= image_tag product.photo, width: "200" if product.photo.attached? %>
    <ul>
        <li><%= product.description %></li>
        <li><%= product.price %> €</li>
    </ul>
</div>

app/views/products/edit.html.erb
<h2><%= t('.title') %>:</h2>
<%= render 'form' %>

app/views/products/index.html.erb
<h1><%= t(".title") %></h1>
<%= render partial: "product", collection: @products %>

app/views/products/new.html.erb
<h1><%= t(".title") %>:</h1>
<%= render "form" %>

app/views/products/show.html.erb
<h1 class="title"><%= @product.title %></h1>
<div>
<%= image_tag @product.photo, width: 200 if @product.photo.attached? %>
</div>
<p class="description"><%= @product.description %></p>
<p class="price"><%= @product.price %>€</p>
<p><%= link_to t(".edit"), edit_product_path(@product.id) %></p>
<p><%= link_to t(".delete"), product_path(@product.id), data: {
                                                          turbo_method: :delete,
                                                          turbo_confirm: t("common.confirm"),
                                                        } %></p>

app/views/shared/_flash.html.erb
<div>
    <%= notice %>
</div>
<div>
    <%= alert %>
</div>

app/views/shared/_footer.html.erb
<!--

<div class="container">
  <footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="/" class="nav-link px-2 text-muted">Inicio</a></li>
      <li class="nav-item"><%= link_to "Compra", products_path, class: "nav-link px-2 text-muted" %></li>
      <li class="nav-item"><%= link_to "Vende", new_product_path, class: "nav-link px-2 text-muted" %></li>
    </ul>
    <p class="text-center text-muted">© 2023 Vendelo!, Inc</p>
  </footer>
</div>

-->

app/views/shared/_header.html.erb
<a href="/"><h1>Vendelo</h1></a>
<%= link_to t(".add"), new_product_path %>
<%= link_to t(".categories"), categories_path %>